repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=40000, --enforce-all]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: limit-staged-files
        name: limit number of staged files
        language: system
        pass_filenames: false
        stages: [pre-commit]
        entry: bash -c '
          n=$(git diff --cached --name-only | wc -l);
          max=50;
          if [ "$n" -gt "$max" ]; then
          echo "$n files staged (> $max)." >&2;
          exit 1;
          fi'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        stages: [pre-push]
        args: [--config-file=pyproject.toml]
        additional_dependencies:
          - pandas-stubs
          - types-PyYAML
          - types-aiofiles
          - types-cachetools
          - types-click
          - types-python-dateutil
          - types-python-slugify
          - types-pytz
          - types-redis
          - types-requests
          - types-seaborn
          - types-setuptools
          - types-six
          - types-tabulate
          - types-toml
